package com.sakayori.music.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF7AA7FF)
val md_theme_dark_onPrimary = Color(0xFF00224F)
val md_theme_dark_primaryContainer = Color(0xFF1A3478)
val md_theme_dark_onPrimaryContainer = Color(0xFFDDE6FF)
val md_theme_dark_secondary = Color(0xFFB8C5E0)
val md_theme_dark_onSecondary = Color(0xFF222F49)
val md_theme_dark_secondaryContainer = Color(0xFF37455E)
val md_theme_dark_onSecondaryContainer = Color(0xFFD8E2F9)
val md_theme_dark_tertiary = Color(0xFF9DB0E8)
val md_theme_dark_onTertiary = Color(0xFF1F2A4D)
val md_theme_dark_tertiaryContainer = Color(0xFF364365)
val md_theme_dark_onTertiaryContainer = Color(0xFFDEE6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF000000)
val md_theme_dark_onBackground = Color(0xFFE4E6F0)
val md_theme_dark_surface = Color(0xFF000000)
val md_theme_dark_onSurface = Color(0xFFE4E6F0)
val md_theme_dark_surfaceVariant = Color(0xFF1A2238)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8CFE0)
val md_theme_dark_outline = Color(0xFF8B95AE)
val md_theme_dark_inverseOnSurface = Color(0xFF0F1424)
val md_theme_dark_inverseSurface = Color(0xFFDDE2EC)
val md_theme_dark_inversePrimary = Color(0xFF2F4A91)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7AA7FF)
val md_theme_dark_outlineVariant = Color(0xFF2C3552)
val md_theme_dark_scrim = Color(0xFF000000)

val md_theme_dark_dim_background = Color(0xFF0A1224)
val md_theme_dark_dim_surface = Color(0xFF0A1224)
val md_theme_dark_dim_surfaceVariant = Color(0xFF1A2238)

val md_theme_light_primary = Color(0xFF2952C5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD7E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001847)
val md_theme_light_secondary = Color(0xFF525E7E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDAE2FB)
val md_theme_light_onSecondaryContainer = Color(0xFF0F1A2D)
val md_theme_light_tertiary = Color(0xFF45599E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDCE2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001551)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF9FBFF)
val md_theme_light_onBackground = Color(0xFF1A1C28)
val md_theme_light_surface = Color(0xFFF9FBFF)
val md_theme_light_onSurface = Color(0xFF1A1C28)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EE)
val md_theme_light_onSurfaceVariant = Color(0xFF43485B)
val md_theme_light_outline = Color(0xFF74798C)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3035)
val md_theme_light_inversePrimary = Color(0xFFB0C7FF)
val md_theme_light_surfaceTint = Color(0xFF2952C5)
val md_theme_light_outlineVariant = Color(0xFFC3C8DA)
val md_theme_light_scrim = Color(0xFF000000)

val colorPrimaryDark = Color(0x19000000)
val back_button_color = Color(0x197E7E7E)

val checkedFilterColor = Color(0xff343a4d)

val shimmerBackground = Color(0x7E2A3142)
val shimmerLine = Color(0xFF3D4660)

val test = Color(0x00FFFFFF)
val overlay = Color(0x32242424)
val blackMoreOverlay = Color(0x8f242424)

val seed = Color(0xFF4F7FFF)

val bottomBarSeedDark = Color(0xff3D6ACC)

val customGray = Color(0x40ECECEC)
val customDarkGray = Color(0x40383535)

val white = Color(0xFFFFFFFF)

val transparent = Color(0x00000000)
